# Generated by Django 2.0.3 on 2018-04-21 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_mobileverifyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileverifyrecord',
            options={'verbose_name': '手机验证码', 'verbose_name_plural': '手机验证码'},
        ),
        migrations.AlterField(
            model_name='mobileverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='mobileverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '密码找回')], max_length=16, verbose_name='类型'),
        ),
    ]
