# Generated by Django 2.0.3 on 2018-04-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180421_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
