# Generated by Django 2.0.3 on 2018-04-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180423_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
