# Generated by Django 2.0.3 on 2018-04-18 19:09

import clothes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),

        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='商品名')),
                ('flower',models.CharField(default='', max_length=120, verbose_name='花型')),
                ('sleeve', models.CharField(choices=[('long', '长袖'), ('medium', '中袖'), ('short', '短袖'), ('none', '背心')], max_length=20, verbose_name='袖型')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('sold', models.IntegerField(verbose_name='销量')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', related_query_name='clothing', to='clothes.Brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '服装',
                'verbose_name_plural': '服装',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='棉', max_length=20, unique=True, verbose_name='面料')),
            ],
            options={
                'verbose_name': '面料',
                'verbose_name_plural': '面料',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='季节')),
            ],
            options={
                'verbose_name': '季节',
                'verbose_name_plural': '季节',
            },
        ),
        migrations.CreateModel(
            name='SizeToStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], verbose_name='大小')),
            ],
            options={
                'verbose_name': '尺寸和款式',
                'verbose_name_plural': '尺寸和款式',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='标准', max_length=30, unique=True, verbose_name='款式')),
            ],
            options={
                'verbose_name': '款式',
                'verbose_name_plural': '款式',
            },
        ),
        migrations.AddField(
            model_name='sizetostyle',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', related_query_name='sizes', to='clothes.Style', verbose_name='款式'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', related_query_name='clothing', to='clothes.Fabric', verbose_name='面料'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='season',
            field=models.ManyToManyField(related_name='clothes', related_query_name='clothing', to='clothes.Season', verbose_name='季节'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='size_to_style',
            field=models.ManyToManyField(related_name='clothes', related_query_name='clothing', to='clothes.SizeToStyle', verbose_name='大小及款式'),
        ),
        migrations.AlterUniqueTogether(
            name='sizetostyle',
            unique_together={('name', 'style')},
        ),
    ]
