# Generated by Django 2.0.3 on 2018-04-18 19:15

import clothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
    ]
