# Generated by Django 2.0.3 on 2018-04-19 11:05

import clothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20180418_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='flower',
            field=models.CharField(default='', max_length=20, verbose_name='花型'),
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='clothes',
            unique_together={('brand', 'fabric', 'sleeve', 'flower')},
        ),
    ]
