# Generated by Django 2.0.3 on 2018-04-19 17:46

import clothes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20180419_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='黑色', max_length=20, unique=True, verbose_name='颜色')),
                ('colorImg', models.ImageField(default='image/default.jpg', upload_to=clothes.models.Color.color_path, verbose_name='图片')),
            ],
            options={
                'verbose_name': '颜色管理',
                'verbose_name_plural': '颜色管理',
            },
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': '款型', 'verbose_name_plural': '款型'},
        ),
        migrations.AlterModelOptions(
            name='sizetostyle',
            options={'verbose_name': '尺码和特点', 'verbose_name_plural': '尺码和特点'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': '特点', 'verbose_name_plural': '特点'},
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='season',
            new_name='seasons',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='size_to_style',
        ),
        migrations.AddField(
            model_name='clothes',
            name='size_to_styles',
            field=models.ManyToManyField(related_name='clothes', related_query_name='clothing', to='clothes.SizeToStyle', verbose_name='尺码及特点'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='sold',
            field=models.IntegerField(default=1000, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='sizetostyle',
            name='name',
            field=models.IntegerField(choices=[(70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95')], verbose_name='尺码'),
        ),
        migrations.AlterField(
            model_name='sizetostyle',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', related_query_name='sizes', to='clothes.Style', verbose_name='特点'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(default='标准', max_length=30, unique=True, verbose_name='特点'),
        ),
        migrations.AddField(
            model_name='color',
            name='clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', related_query_name='colors', to='clothes.Clothes', verbose_name='款型'),
        ),
    ]
