# Generated by Django 2.0.3 on 2018-04-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20180419_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='index',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
