# Generated by Django 2.0.3 on 2018-04-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_season_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
