# Generated by Django 2.0.3 on 2018-04-26 15:41

import clothes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_auto_20180422_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', related_query_name='clothes', to='clothes.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', related_query_name='clothes', to='clothes.Fabric', verbose_name='面料'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='seasons',
            field=models.ManyToManyField(related_name='clothes', related_query_name='clothes', to='clothes.Season', verbose_name='季节'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size_to_styles',
            field=models.ManyToManyField(related_name='clothes', related_query_name='clothes', to='clothes.SizeToStyle', verbose_name='尺码及特点'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.CharField(default='黑色', max_length=20, unique=True, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='colorImg',
            field=models.ImageField(default='image/default.jpg', upload_to=clothes.models.Color.color_path, verbose_name='图片'),
        ),
    ]
