# Generated by Django 2.0.3 on 2018-04-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_auto_20180426_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='flower',
            field=models.CharField(default='', max_length=120, verbose_name='花型'),
        ),
    ]
