# Generated by Django 2.0.3 on 2018-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_auto_20180426_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='sleeve',
            field=models.CharField(choices=[('长袖', '长袖'), ('中袖', '中袖'), ('短袖', '短袖'), ('背心', '背心')], max_length=20, verbose_name='袖型'),
        ),
    ]
