# Generated by Django 2.0.3 on 2018-04-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_auto_20180426_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': '款型颜色管理', 'verbose_name_plural': '款型颜色管理'},
        ),
        migrations.AlterField(
            model_name='color',
            name='clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', related_query_name='colors', to='clothes.Clothes', verbose_name='款型'),
        ),
        migrations.AddField(
            model_name='color',
            name='flower',
            field=models.CharField(default='', max_length=120, verbose_name='花型'),
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='flower',
        ),
        migrations.AlterUniqueTogether(
            name='clothes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clothes',
            name='name',
            field=models.CharField(default='K1', max_length=20, verbose_name='名称'),
        ),
    ]
