# Generated by Django 2.0.3 on 2018-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_auto_20180427_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(default='K1', max_length=20, unique=True, verbose_name='名称'),
        ),
    ]
